### ISSUE TITLE
I can search weather of 'asdva' city

### ISSUE THREAD

**Issue by xtabbas** [ShafiqEssani/ReactWeatherApp#11]
please look?

**Comment by shafiqshams** [comment]
haha dude its because of the openWeatherMap API fault.
>Goto the About tabs > click openWeatherMap https://openweathermap.org/.
> there you can search the weather of any city.

I'm so not guilty about this but ashamed about your thinking because you're working with react which is a definite front-end, you really don't care from where the data is coming and still you dont know these API stuff. I pity on you boy! Go learn some Node, you badly need it. #Coward

**Comment by touqeerkhan11** [comment]
How about you go and fuck yourself? You are fool who cant even make a weather app that don't show trash results!!! You are a shame on this whole world as you are a curse to the universe. I hope you die of your own guilt of being such a poor coder. I mean asdva is a city your dad created? you live in this kind of city? are you a fool? you are a dumbass if you live in asdva city!!! go to your planet where you have a city named asdva and do us all a favor and stop breathing our air of earth because this planet is not for ignorant bigots like you who think there is a city named asdva. what a foolish app

**Comment by shafiqshams** [comment]
Yes bro, this issue exists and I'm currently working on it to fix this blunder.
Thanks 👍

**Comment by shafiqshams** [comment]
Resolved.
Check out the latest master pull.
